server:
  port: 9004

spring:
  application:
    name: distributed-order-service
  cloud:
    #Registration Center Address
    nacos:
      discovery:
        server-addr: 8.130.44.244:8848

  #message queue
  rabbitmq:
    host: 8.130.44.244
    port: 5672
    virtual-host: /
    password: password
    username: admin
    #Enable manual confirmation messages
    listener:
      simple:
        acknowledge-mode: manual

#Database Configuration
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://8.130.44.244:3306/cafe_order?allowPublicKeyRetrieval=true&useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: ds
    password: distributedsystem

#redis Configuration
  redis:
    host: 8.130.44.244
    port: 8000
    password: 123456


#Configure plus to print sql logs
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


feign:
  client:
    config:
      default:
        connectTimeout: 10000 # Connection timeout in milliseconds
        readTimeout: 30000 # Read timeout in milliseconds

#Set the log level, ERROR/WARN/INFO/DEBUG, the default is INFO and above to display.
logging:
  level:
    root: INFO




#Customize message queue configuration, send lock inventory message - "delay exchange - "lock.queue - "dead letter exchange - "release.queue
mqconfig:
  #delay queue, can't be listened to for consumption
  order_close_delay_queue: order.close.delay.queue

  #Delay queue for forwarding messages after they expire
  order_close_queue: order.close.queue

  #exchange
  order_event_exchange: order.event.exchange

  #Route key to the delayed queue
  order_close_delay_routing_key: order.close.delay.routing.key

  #key for message expiration, release queue, dead message queue.
  order_close_routing_key: order.close.routing.key

  #Message expiration time, milliseconds, temporarily changed to 5-minute timed order close
  ttl: 60000


#Alipay Configuration
alipay:
  #Payment success return page
  success_return_url: https://google.com

  #Alipay notification callback interface, Ant Gold Open Platform application backend also needs to be configured with the corresponding address
  callback_url: https://google.com
