apiVersion: v1
kind: Service
metadata:
  name: distributed-coupon-service
spec:
  selector:
    app: distributed-coupon-service
  ports:
    - protocol: TCP
      port: 9002
      targetPort: 9002
  type: LoadBalancer
