apiVersion: v1
kind: Service
metadata:
  name: distributed-product-service
spec:
  selector:
    app: distributed-product-service
  ports:
    - protocol: TCP
      port: 9003
      targetPort: 9003
  type: LoadBalancer
