apiVersion: apps/v1
kind: Deployment
metadata:
  name: distributed-user-service
spec:
  replicas: 3
  selector:
    matchLabels:
      app: distributed-user-service
  template:
    metadata:
      labels:
        app: distributed-user-service
    spec:
      containers:
        - name: distributed-user-service
          image: public.ecr.aws/l1r4r3i8/distributed-user-service:latest
          ports:
            - containerPort: 9001

---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: distributed-user-service-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: distributed-user-service
  minReplicas: 3
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80

