apiVersion: v1
kind: Service
metadata:
  name: distributed-user-service
spec:
  selector:
    app: distributed-user-service
  ports:
    - protocol: TCP
      port: 9001
      targetPort: 9001
  type: LoadBalancer
