server:
  port: 9001

spring:
  application:
    name: distributed-user-service
  cloud:
    nacos:
      discovery:
        server-addr: 8.130.44.244:8848


  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/cafe_user?allowPublicKeyRetrieval=true&useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: zzf19970112472X
#redis
  redis:
    host: 8.130.44.244
    port: 8000
    password: 123456

#mail
  mail:
    host: smtp.163.com
    username: zhangzhuofan2019@163.com
    password: LETAVMOQRWIJSILN
    from: zhangzhuofan2019@163.com #
    properties.mail.smtp.starttls.enable: true
    properties.mail.smtp.starttls.required: true
    properties.mail.smtp.ssl.enable: true
    default-encoding: utf-8

#print sql log
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


#log：ERROR/WARN/INFO/DEBUG
logging:
  level:
    root: INFO


#ali cloud OSS
aliyun:
  oss:
    endpoint: oss-cn-shenzhen.aliyuncs.com
    access-key-id: LTAI4GJR7bL8JEzBv7zx69J4
    access-key-secret: CNfxHJeTTLlFQA2a2X5BprjqjK047l
    bucketname: xdclass-1024shop-img
