server:
  port: 9003

spring:
  application:
    name: distributed-product-service
  cloud:
    nacos:
      discovery:
        server-addr: 8.130.44.244:8848
  rabbitmq:
    host: 8.130.44.244
    port: 5672
    virtual-host: /
    password: password
    username: admin
    listener:
      simple:
        acknowledge-mode: manual

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/cafe_product?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: zzf19970112472X

  redis:
    host: 8.130.44.244
    port: 8000
    password: 123456


mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


logging:
  level:
    root: INFO




mqconfig:
  stock_release_delay_queue: stock.release.delay.queue

  stock_release_queue: stock.release.queue

  stock_event_exchange: stock.event.exchange

  stock_release_delay_routing_key: stock.release.delay.routing.key

  stock_release_routing_key: stock.release.routing.key

  ttl: 360000
